const PREFIXES = {
    "duct": "lead",
    "ex": "out",
    "fer": "carry",
    "hema": "blood",
    "homo": "same",
    "hydro": "water",
    "hypo": "under",
    "micro": "small",
    "mono": "one",
    "neuro": "nerve",
    "omni": "all",
    "pan": "all",
    "pend": "hang",
    "penta": "five",
    "phon": "sound",
    "photo": "light",
    "poly": "many",
    "proto": "first",
    "pseudo": "false",
    "re": "again",
    "spec": "look",
    "tele": "far",
    "tomy": "cut",
    "vid": "look",
    "viv": "life"
};
