const PREFIXES = {
    "vita" : "life",
    "demo" : "people",
    "stereo" : "solid",
    "ism" : "doctrine",
    "cogn" : "know",
    "sur" : "over",
    "alter" : "other",
    "astr" : "star",
    "dyna" : "power",
    "chron" : "time",
    "hyper" : "over",
    "luna" : "moon",
    "octa" : "eight",
    "gyro" : "turn",
    "contra" : "against",
    "geo" : "earth",
    "helio" : "sun",
    "thermo" : "heat",
    "tetra" : "four",
    "meter" : "measure",
    "scope" : "look",
    "son" : "sound",
    "dec" : "ten",
    "stell" : "star",
    "amat" : "love"
};
