const PREFIXES = {
    "morph": "shape",
    "vest": "clothes",
    "bene": "good",
    "pond": "weight",
    "corp": "body",
    "dorm": "sleep",
    "pater": "father",
    "nov": "new",
    "punct": "point",
    "ject": "throw",
    "tion": "act",
    "tion": "state",
    "loco": "place",
    "dox": "opinion",
    "amphi": "both",
    "magn": "great",
    "eu": "good",
    "endo": "within",
    "phobia": "fear",
    "ortho": "straight",
    "put": "think",
    "ver": "true",
    "matri": "mother",
    "mega": "large",
    "pop": "people",
    "sangui": "blood"
};
