const ROOTS = {
  path: { definition: "feeling", examples: ["sympathy", "pathetic", "pathos", "telepathy", "empathy", "apathy", "idiopathy"] },
  a: { definition: "not", examples: ["amoral", "amorphous", "atheist", "apathy", "agraphia", "apolitical", "aphasia", "achromatic"] },
  nomy: { definition: "law", examples: ["astronomy", "economy", "Deuteronomy", "taxonomy", "heteronomy", "nomothetic"] },
  fid: { definition: "faith", examples: ["infidel", "fidelity", "confidence", "diffident", "bona fide", "fiduciary", "perfidy"] },
  caco: { definition: "bad", examples: ["cacophony", "cacography", "cacodemon", "cacoethes", "cacodyl", "cacology"] },
  hetero: { definition: "different", examples: ["heterodox", "heteromorphic", "heterogeneous", "heterosexual", "heteronym"] },
  sci: { definition: "know", examples: ["science", "conscience", "prescience", "omniscience", "scientism", "sciolist"] },
  graph: { definition: "write", examples: ["bibliography", "photograph", "autograph", "polygraph", "stenography"] },
  lat: { definition: "side", examples: ["bilateral", "unilateral", "lateral fin", "multilateral", "collateral", "latitude"] },
  lith: { definition: "rock", examples: ["neolithic", "paleolithic", "lithograph", "megalith", "monolith", "lithium", "laccolith"] },
  tract: { definition: "pull", examples: ["tractor", "detract", "retraction", "attractive", "protractor", "contract", "traction"] },
  in: { definition: "in or not", examples: ["inscribe", "insane", "infidel", "indefinite", "incorrigible", "insomnia"] },
  co: { definition: "together", examples: ["cooperate", "coordinating", "coterminous", "colloquy", "coauthor", "cotangent"] },
  phile: { definition: "love", examples: ["philosopher", "audiophile", "bibliophile", "philologist", "philanthropy"] },
  ine: { definition: "nature of", examples: ["porcine", "crystalline", "saturnine", "canine", "ursine", "vulpine", "bovine"] },
  ar: { definition: "relating to", examples: ["pulsar", "stellar", "lunar", "solar", "secular", "columnar", "linear", "circular"] },
  hexa: { definition: "six", examples: ["hexagram", "hexagon", "hexapod", "hexameter", "hexahedron", "hexarchy"] },
  fract: { definition: "break", examples: ["fracture", "infraction", "fraction", "refraction", "refractory", "fractious"] },
  platy: { definition: "flat", examples: ["plateau", "platyhelminthes", "platypus", "plate", "platitude", "platyrrhine"] },
  theo: { definition: "god", examples: ["theology", "pantheism", "atheism", "monotheism", "apotheosis", "henotheism"] },
  fin: { definition: "end", examples: ["final", "define", "infinite", "finial", "finis", "Finisterre", "infinitive", "fin de siecle"] },
  hedron: { definition: "sided object", examples: ["polyhedron", "tetrahedron", "heptahedron", "octahedron", "icosahedron"] },
  ambul: { definition: "walk", examples: ["ambulatory", "somnambulism", "funambulist", "ambulance", "perambulate"] },
  ous: { definition: "full of", examples: ["luminous", "glorious", "loquacious", "vivacious", "garrulous", "anomalous", "zealous"] },
  topo: { definition: "place", examples: ["topographical", "topology", "topic", "topiary", "toponym", "topognosia"] }
};
